# 道順 — Totani の 20 GeV 超過から、なぜ坂本研究室に行き着いたのか

作成: 2026-08-19 / 用途: 口頭試問で「その結論に至った経緯」を自分の言葉で語るため

**各ステップに【確度】を付けた。** ◎=一次資料で確認済 / ○=論文に明記 / △=自分の解釈

---

## 全体の道順（1 枚）

```
[0] Totani (2025): 銀河ハローに 20 GeV のガンマ線超過。暗黒物質対消滅と解釈
        ↓ 自分がやったこと
[1] 独立検証。20.76 GeV で 19.1σ を再現 ── 超過は実在した
        ↓ しかし
[2] 有意度はそのままでない。79 領域の実測で帰無分布の標準偏差は 1.36
    背景モデルの誤差は別の成分に付け替わる (GALPROP 0.56 倍 → ICS 2.35 倍 → IGRB 崩壊)
        ↓ ここで気づいた限界
[3] ガンマ線の解析だけでは「滑らかな放射」と「暗い天体の集団」を区別しきれない
        ↓ 同じ限界は、より古い問題で 10 年以上議論されていた
[4] 銀河中心 GeV 超過 (GCE): 暗黒物質 vs 未分解ミリ秒パルサー の二大説
        ↓ 決着させようとした試み
[5] 光子統計 (NPTF・機械学習) → 背景モデル次第で結論が反転し、決着しない
        ↓ だから別の道が要る
[6] 天体側を「別の波長で数える」── ガンマ線に閉じない検証
        ↓ ミリ秒パルサーはどこから来るか
[7] ミリ秒パルサーは低質量X線連星 (LMXB) を経て生まれる (リサイクル説)
        ↓ LMXB はどう見えるか
[8] LMXB は普段暗く、時々 X線で突発的に増光する
        ↓ ならば
[9] 長期の全天 X線監視で増光を数えれば、隠れた集団の規模を制限できる
        ↓ それをやっている装置と研究室
[10] MAXI (全天X線監視) ── 坂本研究室が運用とデータ解析を担当
        ↓ さらに
[11] 坂本研の柱「重力波源の電磁波対応天体の探査」は、多くが非検出に終わり
     装置の感度から上限を出す研究 ── 自分が卒論でやった作業と同型
```

---

## [0] 出発点 — Totani (2025)

**【確度 ◎】** arXiv:**2507.07209** / JCAP 2025

銀河ハローに、**約 20 GeV にピークを持つ超過**。2 GeV 以下と 200 GeV 以上ではゼロと無矛盾。
NFW-ρ² 形状に合い、暗黒物質対消滅で解釈できるとした。

⚠️ **これは「銀河中心 GeV 超過 (GCE)」とは別の信号である。**

| | **ハロー超過 (Totani)** | **GCE** |
|---|---|---|
| 空間 | ハロー全体、高銀緯まで | 銀河中心の数度以内 |
| ピーク | **20 GeV** | 1–3 GeV |
| 質量 | 0.5–0.8 TeV 級 | 50 GeV 級 |

**この区別を混ぜると口頭試問で即座に落ちる。**

---

## [1] 自分がやったこと — 独立検証

**【確度 ◎ 自分の実測】**

Fermi-LAT の 15 年分 (780 週) を自ら取得し、露出マップからテンプレートフィットまで
解析パイプラインを一から構築。**20.76 GeV で 19.1σ の超過を再現した。**

→ **超過そのものは実在する。** ここは Totani と一致。

---

## [2] しかし、数字はそのままではなかった

**【確度 ◎ 自分の実測】**

- 同じ手法を **79 領域**に適用 → **すべて非検出**。833 個の有意度の最大は +3.46σ
- **対照領域の帰無分布は N(0,1) ではない**: 標準偏差 **1.36**、|σ|>3 が 2.4% (期待 0.27%)
- **背景モデルの誤差が別の成分に付け替わる**:
  GALPROP の生テンプレートが 1.5 GeV で Totani 比 **0.56 倍** (硬すぎ)
  → 不足を ICS が **2.35 倍**で埋める → **IGRB が潰れる**

→ **有意度は背景モデルの扱い方に強く依存する。**

---

## [3] ここで気づいた限界 ★これが道順の要★

**【確度 △ 自分の解釈だが、[5] の先行研究が裏付ける】**

> **ガンマ線の解析だけでは、超過が「滑らかな放射」なのか
> 「暗い天体が多数集まったもの」なのかを区別しきれない。**

理由: ガンマ線望遠鏡は角度分解能が低く、暗い点源を個別に分離できない。
統計的に区別しようとしても、背景モデルの誤差がそこに流れ込む ([5])。

---

## [4] 同じ限界は、GCE で 10 年以上議論されていた

**【確度 ○】** `ref2/1506.05104.pdf` (Bartels+) / `ref2/1506.05124.pdf` (Lee+)

2015 年 6 月、arXiv に**数日以内で 3 本の競合説**が投稿された:

| arXiv | 説 |
|---|---|
| 1506.05104 | ミリ秒パルサー (ウェーブレット解析、10.0σ の塊状構造) |
| 1506.05119 | 宇宙線アウトバースト (Cholis+) |
| 1506.05124 | 未分解点源 (NPTF を発明、超過は点源に完全に吸収される) |

他に**若いパルサー**説 (`ref2/1504.02477.pdf`, O'Leary+)。

→ **暗黒物質は候補の一つにすぎない。**

---

## [5] 光子統計では決着しなかった

**【確度 ○】** `ref2/1904.08430.pdf` (Leane & Slatyer 2019) / `ref2/2507.17804.pdf` (List+ 2026 PRL)

- 2016: NPTF とウェーブレットの**独立 2 手法**が「点源だ」と結論 → 点源説がほぼ定説に
- 2019: **Leane & Slatyer が実データに人工の暗黒物質信号を注入 → 丸ごと点源と誤判定された**
  → 「点源の証拠」は背景モデルの誤りの産物でありうる
- 2026: List+ が空間とエネルギーを同時に扱う機械学習で解析
  → 点源で説明するには **10 万個規模** (従来説の数百個より 2 桁多い)。
  最良の背景モデルでは超過は暗黒物質の予言と無矛盾
  ⚠️ ただし論文自身が「背景モデルの系統次第で必要数は約 1 桁減りうる」と断っている

→ **手法が新しくなるたびに結論が反転する。原因は毎回「背景モデルの不定性」。**
→ 🔥 **これは [2] で自分が実測したことと同じ病理。**

---

## [6] だから「別の波長で天体そのものを数える」

**【確度 ○ 既に出版された論法】**
`ref2/1407.5625.pdf` (Cholis+ 2014) / `ref2/1701.02726.pdf` (Haggard+ 2017)

ガンマ線の中で議論し続けても背景モデル依存から抜けられない。
**ならば、天体候補が本当にその数だけ存在しうるかを、別の波長で確かめればよい。**

Haggard+ 2017 の結論 (原文):
> If MSPs had been responsible for the entirety of the observed excess,
> **INTEGRAL should have detected ~10³ LMXBs** from within a 10° radius around
> the Galactic Center, whereas **only 42 LMXBs** (and 46 additional LMXB
> candidates) have been observed.

→ 超過のうち MSP 起源は **最大 4–23%** (Cholis+ 2014 は **1–5%**)

---

## [7] なぜ X線連星が出てくるのか — ミリ秒パルサーの生まれ方

**【確度 ○ 1980 年代からの教科書的定説 (リサイクル説)】**

```
中性子星が誕生 (速く回転)
   ↓ 数百万年で減速し、光れなくなる (死ぬ)
   ↓ 連星の相方が膨張し、ガスが落ちてくる
【低質量X線連星 (LMXB)】降着円盤が数百万度 → 【X線で光る】
   ↓ ガスの角運動量で再加速 (リサイクル) を何億年も受ける
【ミリ秒パルサー (MSP)】1 秒に数百回転 → 【ガンマ線で光る】
```

**X線連星とミリ秒パルサーは、同じ天体の別の人生段階。**
→ **MSP が多い ⇒ LMXB も多い。LMXB が少ない ⇒ MSP も少ない。**

---

## [8] LMXB は「突発天体」の顔を持つ

**【確度 ○ 教科書】**

降着は一定でない。円盤にガスが溜まり、**ある日一気に落ちて突発的に増光する**
(アウトバースト / X線新星)。

| 状態 | 期間 | 見え方 |
|---|---|---|
| 静穏期 | 数年〜数十年 | **暗すぎて見えない** |
| アウトバースト | 数週間〜数ヶ月 | **急に明るくなる** |

→ **ある瞬間の観測ではほとんど写らない。増光の瞬間を待つしかない。**

---

## [9] だから「長期の全天監視」が要る

**【確度 △ 論法としては [6] の延長。具体的な実施計画は未定】**

> 街の人口を知りたいが全員家の中。しかし住民は時々庭で花火を上げる。
> **15 年間空を見張り、花火の回数を数える。**
> 1 人あたりの花火の頻度が分かれば、総人口が推定できる。

⚠️ **最大の弱点 = 「1 人あたりの頻度」(デューティサイクル) の不定性。**
面接ではここを自分から言うこと。

---

## [10] その装置が MAXI、運用しているのが坂本研究室

**【確度 ◎ 研究室公式サイト原文】** <https://sites.google.com/phys.aoyama.ac.jp/sakamotolab>

> **坂本研では MAXI のデータ解析、そして運用を行っています。**

> **MAXIの観測対象はX線連星、X線新星、活動銀河核やガンマ線バーストなどの
> 時間変動や突発天体です。**

**MAXI ができること / できないこと**

| ✅ | 15 年以上、全天を約 92 分周期で監視。突発増光の長期記録を持つ |
| ❌ | 全天を薄く広く見るため**暗い増光は取りこぼす**。銀河中心方向は混雑して分離が難しい |

→ **MAXI だけで答えは出ない。** Haggard+ が使ったのは INTEGRAL のような
深い指向観測。**MAXI が担うのは「明るい増光の統計」の部分。**

→ 🔑 **本当の価値は、装置を運用している人が近くにいること。**
「見つからなかった」が「無い」ではなく「**この感度では届かなかった**」を意味する、
という区別が日常にある。

---

## [11] 決め手 — 坂本研の柱は「非検出から結論を出す」研究

**【確度 ◎ 論文の原文】**

坂本先生が共著の重力波対応天体探索:

| arXiv | 結果 |
|---|---|
| **1807.01435** | GW151226/170104/170608/170814/170817 を探索 → **"only upper limits on gamma-ray emission are obtained"** (上限のみ) |
| **2207.03621** | LIGO/Virgo O3 の探索 → **"No events have been detected that pass all acceptance criteria."** (非検出) |

**さらに**: Graff, Lien, Baker & **Sakamoto** (2016) `ref2/1509.01228.pdf` は
**装置の検出効率を機械学習でモデル化**した論文 (著者欄に
"TAKANORI SAKAMOTO, ... Aoyama Gakuin University" とフルネーム+所属で明記)。

> ### 坂本研究室は「探して、見つからなくて、そこから上限を言う」を柱にしている。

**そして自分の卒論も同じ**: 79 領域すべて非検出 → 帰無分布を実測 →
「名目 σ は過大評価になっている」を示した。

→ **観測装置を持つ研究室は多いが、「非検出から上限を出すこと」を柱に
している研究室は限られる。** これが行き着いた理由。

---

## 🔴 正直に弱い部分 (聞かれたら認めること)

| 項目 | 実態 |
|---|---|
| 坂本先生自身は GCE も MSP も LMXB 個数調査も論文にしていない | **研究室にとって新しいテーマだと認める** |
| 自分は X線データ解析の経験がない | 「ガンマ線側は自分で組める。X線側はこれから教わる」と分ける |
| **卒論はハロー超過、MSP 説の舞台は GCE。別の信号** | **手法として持ち込むのだと明示する ([0] の表)** |
| デューティサイクルの不定性 | **自分から先に言う** |
